### ISSUE TITLE
Batch processing

### ISSUE THREAD

**Issue by 13559323996** [OnderT/XoFTR#4]
When the number of points extracted from a batch in the coarse matching stage is different, how are these vectors with different lengths stacked in the fine matching stage? Or is it batch_size=1? I don’t seem to see it in the XoFTR and LoFTR codes.
Can I ask you for advice on the batch processing process?

**Comment by OnderT** [comment]
Since different image pairs in the batch produce different numbers of matches, the matches are concatenated along the same dimension. Additionally, a variable keeps track of which batch index each match corresponds to.

I have prepared a demo notebook for batch processing, and you can examine the code for a better understanding.

[Demo notebook](https://github.com/OnderT/XoFTR/blob/main/notebooks/xoftr_demo_batch.ipynb)

Please note that results may vary in batch processing due to batch normalization and padding.
