### ISSUE TITLE
About how to make the matched points evenly distributed on the image

### ISSUE THREAD

**Issue by lishuwei10** [OnderT/XoFTR#6]
Thank you very much for sharing the XoFTR code. I have tried to apply this method in my work. But I observed a phenomenon: the matched points are concentrated in the center of the image, and there are very few at the edge of the image. This leads to the alignment effect of the center of the picture being better and the edge being less ideal when the image is aligned using the homography matrix calculated based on these points. The following are some prediction and alignment results

I would like to ask if this problem can be optimized by setting certain parameters so that the matched points are more evenly distributed on the image? Thank you!

![2_2024-10-29-16-57-18_23 bag_matched](https://github.com/user-attachments/assets/31970b02-67c3-41b0-9bbd-4de7e088197b)
![71_2024-10-29-16-57-18_23 bag_matched](https://github.com/user-attachments/assets/f3eae314-a958-471c-9f15-dd2ff7a80288)
![500_2024-10-29-16-57-18_23 bag_matched](https://github.com/user-attachments/assets/9e617fdd-0d2b-41a0-ba2d-23537f7499b9)

![22_2024-10-29-16-57-18_23 bag_fused](https://github.com/user-attachments/assets/fb084d78-8080-430c-aa7a-8f1c7bde5401)
![58_2024-10-29-16-57-18_23 bag_fused](https://github.com/user-attachments/assets/da0fffd0-8c88-4383-babb-40345bc1269a)
![263_2024-10-29-16-57-18_23 bag_fused](https://github.com/user-attachments/assets/db5f0d8e-8007-44e8-9991-7d42e9c57cd4)

**Comment by OnderT** [comment]
Thank you for your interest in our work.

Since XoFTR was trained on the MegaDepth dataset, which contains mostly buildings and other man-made structures, it is expected to perform better in areas with more details, like buildings, compared to less detailed regions such as the sky, flat roads, or mountain silhouettes. However, I did not notice a consistent pattern where matches are overly concentrated in the center of the images.

Looking at the images you provided, it seems there is some radial distortion. This distortion is stronger toward the edges, so matches in these areas may be flagged as outliers during homography estimation because they don't fit the geometric assumption (planar). Distortion can also negatively affect the overall matching performance, leading to poorer matches at the image edges.

I suggest checking the matches before the homography calculation and outlier removal to see if any correct matches exist at the edges. If distortion seems to be the problem, you could calculate the camera parameters, undistort the images, and try aligning them again.

I hope this helps!
